version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - './app:/app'
    ports:
      - '3000:3000'
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - './api:/api'
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: desafio123
      MYSQL_DATABASE: desafio
      MYSQL_USER: desafio
      MYSQL_PASSWORD: desafio123
    ports:
      - "3306:3306"

volumes:
  db_data: